# - Try to find the CHECK libraries
#  Once done this will define
#
#  CHECK_FOUND - system has check
#  CHECK_INCLUDE_DIRS - the check include directory
#  CHECK_LIBRARIES - check library

IF ( CHECK_INCLUDE_DIR )
    SET(CHECK_FIND_QUIETLY TRUE)
ENDIF (CHECK_INCLUDE_DIR)

FIND_PATH(CHECK_INCLUDE_DIR NAMES check.h)
FIND_LIBRARY(CHECK_LIBRARIES NAMES check libcheck)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHECK DEFAULT_MSG CHECK_INCLUDE_DIR CHECK_LIBRARIES)

MARK_AS_ADVANCED(CHECK_INCLUDE_DIR CHECK_LIBRARIES)
